<?php
$itemCount = 0;
$this->layout('layout/fullpage', [
    'pageConfig' => [
        'load' => 'landing/article-draft'
    ]
]);
?>

<?php $this->section('main'); ?>
<div class="ctn draft">

<h1><?php echo $this->trans('draft'); ?></h1>

<div class="list article-list">
<?php foreach ($this->draftList as $draft) { ?>
    <div class="item">
        <div class="article-title">
            <a href="<?php echo $this->routeUrl('article-update-commit', ['code' => $draft->code]); ?>">
            <?php echo $draft->getTitle(); ?>
            </a>
        </div>
        <div class="prop">
            <?php echo elapsed($draft->changed); ?>
        </div>
    </div>
<?php } ?>
</div><!-- .list -->

<?php echo $this->insert('ctrl/pagination', [
    'page' => $this->page,
    'pagePerCount' => $this->pagePerCount,
    'itemCount' => $itemCount
]); ?>

</div><!-- .ctn -->
<?php $this->append(); ?>
