<?php
$this->layout('layout/fullpage', [
    'pageConfig' => [
        'load' => 'article/commit-update',
        'commitDto' => [
            'articleId' => $this->commitDto->articleId,
            'commitId' => $this->commitDto->commitId,
            'userId' => $this->commitDto->userId,
            'status' => $this->commitDto->status,
            'content' => $this->commitDto->content,
            'created' => $this->commitDto->created,
            'changed' => $this->commitDto->changed,
        ]
    ]
]);

//$escapedContent = str_replace("'", "\'", $this->commitDto->content);
/*
var_dump(htmlspecialchars($this->commitDto->content));
exit();
$escapedContent = str_replace(
    ["'", "\n"],
    ["\'", '\n'],
    $this->commitDto->content
);
 */
$escapedContent = $this->commitDto->content;
$escapedContent = str_replace('\\', '\\\\', $escapedContent);
$escapedContent = str_replace('\'', '\\\'', $escapedContent);
$escapedContent = str_replace("\n", '\n', $escapedContent);
?>

<?php $this->section('script'); ?>
<script>
//window.updateSavedContent('<?php echo $escapedContent; ?>');
</script>
<?php $this->append(); ?>
