<?php
$this->layout('layout/editor-monaco', [
    'pageConfig' => [
        'load' => 'article/commit-update',
        'commitDto' => [
            'articleId' => $this->commitDto->articleId,
            'commitId' => $this->commitDto->commitId,
            'userId' => $this->commitDto->userId,
            'status' => $this->commitDto->status,
            'created' => $this->commitDto->created,
            'changed' => $this->commitDto->changed,
        ]
    ]
]);

$escapedContent = str_replace("'", "\'", $this->commitDto->content);
?>

<?php /*
<?php $this->section('main'); ?>
<?php var_dump($this->commitDto); ?>
<?php $this->replace(); ?>
 */ ?>

<?php $this->section('script'); ?>
<script>
 window.codeEditor.setValue('<?php echo $escapedContent; ?>');
</script>
<?php $this->append(); ?>
