<?php
$this->layout('layout/editor-monaco', [
    'pageConfig' => [
        'load' => 'article/commit-update',
        'commitDto' => [
            'articleId' => $this->commitDto->articleId,
            'commitId' => $this->commitDto->commitId,
            'userId' => $this->commitDto->userId,
            'status' => $this->commitDto->status,
            'created' => $this->commitDto->created,
            'changed' => $this->commitDto->changed,
        ]
    ]
]);

//$escapedContent = str_replace("'", "\'", $this->commitDto->content);
/*
var_dump(htmlspecialchars($this->commitDto->content));
exit();
$escapedContent = str_replace(
    ["'", "\n"],
    ["\'", '\n'],
    $this->commitDto->content
);
 */
$escapedContent = $this->commitDto->content;
$escapedContent = str_replace('\\', '\\\\', $escapedContent);
$escapedContent = str_replace('\'', '\\\'', $escapedContent);
$escapedContent = str_replace("\n", '\n', $escapedContent);
?>

<?php /*
<?php $this->section('main'); ?>
<?php var_dump($this->commitDto); ?>
<?php $this->replace(); ?>
 */ ?>

<?php $this->section('script'); ?>
<?php /*
<textarea id="commit-content" style="display: none">
<?php echo htmlspecialchars($this->commitDto->content); ?>
</textarea>
 */ ?>
<script>
 window.codeEditor.setValue('<?php echo $escapedContent; ?>');
</script>
<?php $this->append(); ?>
