<?php
$localeKey = $this->getLocaleKey();

$pageConfig = $this->pageConfig ? $this->pageConfig : [];
$pageConfig = array_merge($pageConfig, [
    'localeKey' => $localeKey,
    'now' => micro_date()
]);

$isDebug = $this->config->bool('debug');
$cssUrl = $isDebug ? $this->staticUrl('/ui/dev/css/main.css') : $this->staticUrl('/ui/dist/css/main.css');
$jsUrl = $isDebug ? $this->staticUrl('/main/dev/js/main.js') : $this->staticUrl('/main/dist/js/main.js');
?><!DOCTYPE html>
<html lang="<?php echo $localeKey; ?>" prefix="og: http://ogp.me/ns#">
<head>
<?php echo $this->insert('html/meta', ['localeKey', $localeKey]); ?>
<link rel="stylesheet" href="<?php echo $cssUrl; ?>" />
<?php $this->section('head'); ?><?php $this->stop(); ?>
</head>

<body>

<div class="page <?php echo $this->route->getName(); ?>">
<?php $this->section('main'); ?><?php $this->stop(); ?>
</div>

<script type="text/javascript">
window.PageConfig=<?php echo json_encode($pageConfig); ?>;
</script>
<?php $this->section('script'); ?><?php $this->stop(); ?>
<script type="text/javascript" src="<?php echo $jsUrl; ?>"></script>
</body>

</html>
