<?php
$localeKey = $this->getLocaleKey();

$pageConfig = $this->pageConfig ? $this->pageConfig : [];
$pageConfig = array_merge($pageConfig, [
    'localeKey' => $localeKey,
    'now' => micro_date()
]);
$isDebug = $this->config->bool('debug');
?><!DOCTYPE html>
<html lang="<?php echo $localeKey; ?>" prefix="og: http://ogp.me/ns#">
<head>
<?php echo $this->insert('html/meta', ['localeKey', $localeKey]); ?>
<?php $this->section('style'); ?><?php $this->stop(); ?>
<?php if ($isDebug) { ?>
    <link rel="stylesheet" href="<?php echo $this->staticUrl('/ui/dev/main.css'); ?>" />
<?php } else { ?>
    <link rel="stylesheet" href="<?php echo $this->staticUrl('/ui/dist/main.css'); ?>" />
<?php } ?>
</head>

<body>
<?php $this->section('main'); ?><?php $this->stop(); ?>

<script type="text/javascript">
window.PageConfig=<?php echo json_encode($pageConfig); ?>;
</script>
<?php $this->section('script'); ?><?php $this->stop(); ?>
</body>

</html>
